name: Redeploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment Environment'
        required: true
        type: string
      branch:
        description: 'Branch to deploy'
        required: true
        type: string

jobs:
  re_deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
   
    steps:
     - uses: actions/checkout@v3

     - name: Set up Node.js
       uses: actions/setup-node@v3
       with:
        node-version: '20'

     - name: Set up SSH and Deploy
       run: |
        # Create the SSH private key file
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
        chmod 600 private_key

        # Disable host key checking and SSH into the EC2 instance
        ssh -o StrictHostKeyChecking=no -i private_key ${{ vars.EC2_USER }}@${{ vars.EC2_IP}} << 'EOF'
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 856236452116.dkr.ecr.ap-south-1.amazonaws.com
  
          export PORT=${{ vars.PORT}}
          export NODE_ENV=${{ vars.NODE_ENV }}
          export MONGODB_USERNAME=${{ secrets.MONGODB_USERNAME }}
          export MONGODB_PASSWORD=${{ secrets.MONGODB_PASSWORD }}
          export MONGODB_ADDRESS=${{ vars.MONGODB_ADDRESS }}
          export MONGODB_DBNAME=${{ vars.MONGODB_DBNAME }}
          export MONGODB_APPNAME=${{ vars.MONGODB_APPNAME }}
          export AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          export AWS_REGION=${{ vars.AWS_REGION }}
          export AWS_BUCKET_NAME=${{ vars.AWS_BUCKET_NAME }}
          export SMTP_HOST=${{ vars.SMTP_HOST }}
          export SMTP_PORT=${{ vars.SMTP_PORT }}
          export SMTP_USERNAME=${{ secrets.SMTP_USERNAME }}
          export SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD}}
          export SMTP_TLS_CIPHERS=${{ vars.SMTP_TLS_CIPHERS}}
          export EMAIL_FROM=${{ vars.EMAIL_FROM }}
          export JWT_SECRET=${{ secrets.JWT_SECRET }}
          export JWT_ACCESS_EXPIRATION_MINUTES=${{ vars.JWT_ACCESS_EXPIRATION_MINUTES }}
          export JWT_REFRESH_EXPIRATION_DAYS=${{ vars.JWT_REFRESH_EXPIRATION_DAYS }}
          export JWT_RESET_PASSWORD_EXPIRATION_MINUTES=${{ vars.JWT_RESET_PASSWORD_EXPIRATION_MINUTES }}
          export JWT_VERIFY_EMAIL_EXPIRATION_MINUTES=${{ vars.JWT_VERIFY_EMAIL_EXPIRATION_MINUTES }}
          export OPEN_SEARCH_DOMAIN_URL=${{ vars.OPEN_SEARCH_DOMAIN_URL }}
          export OPEN_SEARCH_USERNAME=${{ secrets.OPEN_SEARCH_USERNAME }}
          export OPEN_SEARCH_PASSWORD=${{ secrets.OPEN_SEARCH_PASSWORD }}
          export VAPID_PUBLIC_KEY=${{ secrets.VAPID_PUBLIC_KEY }}
          export VAPID_PRIVATE_KEY=${{ secrets.VAPID_PRIVATE_KEY }}
          export WEJHA_URL=${{ vars.WEJHA_URL }}
          export ADMIN_URL=${{ vars.ADMIN_URL }}
          export SSE_INSTANCE_URL=${{ vars.SSE_INSTANCE_URL }}
          export RAZORPAY_KEY_SECRET=${{ secrets.RAZORPAY_KEY_SECRET }}
          export RAZORPAY_KEY_ID=${{ secrets.RAZORPAY_KEY_ID }}
          export WEBHOOK_SECRET=${{ secrets.WEBHOOK_SECRET }}
          export YOUTUBE_DURATION_API_KEY=${{ secrets.YOUTUBE_DURATION_API_KEY }}
          export GET_POS_IT_EASY_INVENTORIES_URL=${{ vars.GET_POS_IT_EASY_INVENTORIES_URL }}
          export CMS_RECAPTCHA_SECRET_KEY=${{ secrets.CMS_RECAPTCHA_SECRET_KEY }}
          export ADMIN_RECAPTCHA_SECRET_KEY=${{ secrets.ADMIN_RECAPTCHA_SECRET_KEY }}
          export WEBSITE_RECAPTCHA_SECRET_KEY=${{ secrets.WEBSITE_RECAPTCHA_SECRET_KEY }}
          export MOBILE_APP_RECAPTCHA_SECRET_KEY=${{ secrets.MOBILE_APP_RECAPTCHA_SECRET_KEY }}
          export RECAPTCHA_PROJECT_KEY=${{ vars.RECAPTCHA_PROJECT_KEY }}
          export GOOGLE_APPLICATION_CREDENTIALS=${{ vars.GOOGLE_APPLICATION_CREDENTIALS }}
          export URWAY_CREATE_RECURRING_PAYMENT_URL=${{ vars.URWAY_CREATE_RECURRING_PAYMENT_URL }}
          export URWAY_CANCEL_RECURRING_PAYMENT_URL=${{ vars.URWAY_CANCEL_RECURRING_PAYMENT_URL }}
          export URWAY_TERMINAL_ID=${{ secrets.URWAY_TERMINAL_ID }}
          export URWAY_MERCHANT_IP=${{ secrets.URWAY_MERCHANT_IP }}
          export URWAY_PASSWORD=${{ secrets.URWAY_PASSWORD }}
          export URWAY_SECRET_KEY=${{ secrets.URWAY_SECRET_KEY }}
          export URWAY_CUSTOMER_IP=${{ secrets.URWAY_CUSTOMER_IP }}


          docker compose pull
          docker compose down
          docker compose up -d 
          docker image prune -f


     - name: Log deployment message
       run: |
           echo "Redeployment triggered with message: ${{ github.event.inputs.deployment_message }}"
